### ISSUE TITLE
Not getting filtered responses

### ISSUE THREAD

**Issue by krestaino** [WP-API/rest-filter-response-fields#2]
I love this plugin idea, but for some reason it's not working for me. The 2 following URLs are retuning the same thing. I was expecting a list of 10 posts with only titles and excepts, but instead I'm getting everything.

`/wp-json/wp/v2/posts?orderby=date&per_page=10`

`/wp-json/wp/v2/posts?fields=title,excerpt&orderby=date&per_page=10`

I can't even get `/wp-json/wp/v2/posts?fields=title,excerpt` to work, it just returns all the posts. Any idea what's going on? The Wordpress install is brand new (4.8) and no other plugins are installed.

**Comment by stevehenty** [comment]
Try prefixing `fields` with an underscore: `/wp-json/wp/v2/posts?_fields=title,excerpt`

**Comment by krestaino** [comment]
That isn't working either. 😕 

Closing this issue. I resolved it using [this plugin](https://github.com/svrooij/rest-api-filter-fields).
